import argparse
import os
import traceback
import gc
from pathlib import Path
import datasets
import torch
from torch import utils
from torch.utils.data import DataLoader
import numpy as np 
from dotenv import load_dotenv 
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import PreTrainedModel, PreTrainedTokenizer, PreTrainedTokenizerFast
from sentence_transformers import SentenceTransformer
from context_cite import ContextCiter
from context_cite.utils import _get_response_logit_probs, aggregate_logit_probs
from tqdm.auto import tqdm
import re
from typing import List, Union
from numpy.typing import NDArray
from utils import load_json, save_json, load_data, load_datapoint, load_cc_prompt_template, split_model_answer, load_model, get_nli_entailment_probs, CC_GENERATE_KWARGS
from longcite_utils import LongCiteContextCiter, LongCiteContextPartitioner, LONGCITE_GENERATE_KWARGS, LONGCITE_PROMPT_TEMPLATE

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

def parse_args():
    parser = argparse.ArgumentParser(description="Calculate answer attribution scores using different attribution methods.")
    parser.add_argument("--dataset", type=str, choices=["cnn_daily_mail", "druid", "averitec", "averitec_short_ans", "averitec_web_evidence", "averitec_web_evidence_short_ans", "multifieldqa_en"], default=None, required=True, help="Which dataset to use.")
    parser.add_argument("--model_name", type=str, choices=["meta-llama/Llama-3.1-8B-Instruct", "THUDM/LongCite-llama3.1-8b"], default="THUDM/LongCite-llama3.1-8b", help="Huggingface name of model to use.")
    parser.add_argument("--attr_methods", type=str, nargs="+", choices=["context_cite", "semantic_similarity", "leave_one_out", "nli_post_hoc_naive", "nli_post_hoc_sliding_window", "nli_post_hoc_greedy_sampling", "llm_post_hoc", "longcite_llm_direct"], required=True, help="Which answer attribution methods to use.")
    parser.add_argument("--use_longcite", action="store_true", help="Whether to use the ContextCiter class modified for use with LongCite model and tokenizer and whether to attribute answer and statements as generated by LongCite model.")
    parser.add_argument("--cc_num_ablations", type=int, nargs="+", choices=[32, 64, 128, 256], help="How many ablations to use if ContextCite is used as attribution method.")
    parser.add_argument("--sliding_window_lengths", type=int, nargs="+", choices=[3,5], help="How many sentences to include per context window if NLI with sliding windows is used as attribution method.")
    parser.add_argument("--results_path", type=str, default="Results/results.json", help="Path to the file where attribution scores and experiment results are stored.")
    parser.add_argument("--n_samples", type=int, default=-1, help="How many data points to sample from the dataset.")
    parser.add_argument("--start_idx", type=int, default=0, help="Data starting index.")
    parser.add_argument("--cc_batch_size", type=int, default=8, help="Batch size to use in ContextCiter for performing inference using ablated contexts.")

    return parser.parse_args()

def get_results_metadata(cc: ContextCiter, res: dict):
    """Add key-structure to the results dict for saving meta-info and the attribution scores."""
    # check if metadata already exists from previous run, if yes then set the cc model answer / output
    if res.get("model_output_full"):
        cc._cache["output"] = res["model_output_full"]
    else:
        # split the answer in statements/sentences and get corresponding starting and ending indices
        answer_statements, char_spans = split_model_answer(cc)
        
        res["query"] = cc.query
        res["model_answer"] = cc.response.strip()
        res["answer_statements"] = answer_statements
        res["num_answer_statements"] = len(answer_statements)
        res["answer_statement_char_spans"] = char_spans
        res["model_output_full"] = cc._cache["output"]
        res["num_sources"] = len(cc.sources)  

    # attribution scores
    if "methods" not in res.keys():
        res["methods"] = {}          

    return res, cc

#--- Answer Attribution Methods ---#
def compute_attributions_context_cite(cc_kwargs: dict, res: dict, cc_num_ablations: List[int], use_longcite: bool):
    """Compute ContextCite attributions for each given number of ablations."""

    def cc_compute_attributions(cc: ContextCiter, res: dict):
        """Compute attributions for each sentence in the model answer and write it to the results dict."""

        char_spans = res["answer_statement_char_spans"]

        attr_scores = []
        for start_idx, end_idx in char_spans:
            attr_scores_sent = cc.get_attributions(start_idx=start_idx, end_idx=end_idx, as_dataframe=False)
            attr_scores.append(attr_scores_sent.tolist())   # convert to list for json serialization

        # add attribution scores for the specific method (always overwrite if there were existing ones)
        method_name = f"context_cite_{cc.num_ablations}"    # for context cite include the number of ablations in the method name
        res["methods"][method_name] = {
            "attr_scores": attr_scores,
        }
        return res
    
    if len(cc_num_ablations) == 0:   # check that at least one option for num_ablations is given
        raise ValueError("Number(s) of ablations must be specified when using ContextCite for attribution.")

    for num_ablations in cc_num_ablations: 
        # instantiate new ContextCiter for each num_ablations and set model response
        cc = LongCiteContextCiter(**cc_kwargs, num_ablations=num_ablations) if use_longcite else ContextCiter(**cc_kwargs, num_ablations=num_ablations)
        cc._cache["output"] = res["model_output_full"]

        # compute attribution scores
        res = cc_compute_attributions(cc, res)

    return res

def compute_attributions_semantic_similarity(cc: ContextCiter, embedding_model: SentenceTransformer, res: dict):
    """
    Compute answer attribution scores based on semantic similarity for each sentence in the model answer.
    The sentences in the model answer and the context are embedded using a sentence embedding model and
    their cosine similarities are used as attribution scores.
    """

    answer_statements = res["answer_statements"]
    context_sentences = cc.sources

    # embed sentences
    with torch.inference_mode():
        answer_embeddings = embedding_model.encode(answer_statements)
        context_embeddings = embedding_model.encode(context_sentences) 

    # compute cosine similarities for each pair of answer and context sentence
    embedding_model.similarity_fn_name = "cosine" 
    cos_similarities = embedding_model.similarity(answer_embeddings, context_embeddings)    # (n_sentences, n_sources)

    # write to results dict
    res["methods"]["semantic_similarity"] = {
        "attr_scores": cos_similarities.tolist(),
    }
    return res

def compute_attributions_leave_one_out(cc: ContextCiter, res: dict):
    """Compute answer attribution scores based on leave-one-out baseline for each sentence in the model answer."""

    def create_masks(cc: ContextCiter) -> List[NDArray[np.bool_]]:
        """
        Set up boolean masks for calculating the log-prob drop for each context source.
        
        Returns:
            masks (List[NDArray[np.bool_]]):
                List of boolean masks. First element is a full masks with all entries equal to 1.
                For the following entries exactly one entry is set to 0 and all others remain 1;
                one entry per context source. Shape: (n_sources+1, n_sources)
        """

        masks = []
        masks.append(np.ones(len(cc.sources), dtype=np.bool_))  # full mask 
        for i in range(len(cc.sources)):
            mask = np.ones(len(cc.sources), dtype=np.bool_)
            mask[i] = False
            masks.append(mask)

        return masks
    
    def create_dataset(cc: ContextCiter, masks: List[NDArray[np.bool_]]):
        """
        Create "dataset" with input tokens and output tokens (labels) for different ablations.
        Based on ContextCite utils._create_regression_dataset function.
        """

        data_dict = {
            "input_ids": [],
            "attention_mask": [],
            "labels": [],
        }

        response_ids = cc._response_ids # token indices of the complete response
        for mask in masks:
            prompt_ids = cc._get_prompt_ids(mask=mask)  # token indices of the prompt with sources ablated according to the mask
            input_ids = prompt_ids + response_ids

            data_dict["input_ids"].append(input_ids)
            data_dict["attention_mask"].append([1] * len(input_ids))
            data_dict["labels"].append([-100] * len(prompt_ids) + response_ids) # label only for response part

        return datasets.Dataset.from_dict(data_dict)
    

    # create masks: one full mask and one per context source where exactly one source is ablated
    masks = create_masks(cc)

    # create "dataset" with input tokens for the different ablations and output tokens (labels) 
    dataset = create_dataset(cc, masks)

    # calculate logit probabilities for all answer tokens for each of the context ablations
    # shape: (n_masks, n_answer_tokens)
    logit_probs = _get_response_logit_probs(
        dataset, cc.model, cc.tokenizer, len(cc._response_ids), cc.batch_size
    )

    char_spans = res["answer_statement_char_spans"]
    attr_scores = []
    for start_idx, end_idx in char_spans:

        # aggregate logit_probs and convert to log_prob for the current sentence
        ids_start_idx, ids_end_idx = cc._indices_to_token_indices(start_idx, end_idx)
        logit_probs_sent = logit_probs[:, ids_start_idx:ids_end_idx]

        log_probs = []  # final log probabilites for the answer with context ablations
        for i in range(logit_probs_sent.shape[0]):
            log_probs.append(aggregate_logit_probs(logit_probs_sent[i:i+1,:], output_type="log_prob").item())

        # 5. compute differences with full context, normalize the result by number of answer tokens (in the sentence)
        n_answer_tokens_sent = logit_probs_sent.shape[1]
        log_prob_drops = (np.array(log_probs[0]) - np.array(log_probs[1:])) / n_answer_tokens_sent

        attr_scores.append(log_prob_drops.tolist())


    # write to results dict
    res["methods"]["leave_one_out"] = {
        "attr_scores": attr_scores,
    }
    return res

def compute_attributions_nli_post_hoc_naive(cc: ContextCiter, nli_tokenizer: Union[PreTrainedTokenizer, PreTrainedTokenizerFast], 
                                            nli_model: PreTrainedModel, res: dict):
    """
    Compute answer attribution scores using post-hoc attribution with the DeBERTa model for natural language 
    inference for each sentence in the model answer. We take as attribution scores the predicted probability
    for entailment from the NLI model using the answer sentence to attribute as hypothesis and each of the 
    context sentences as premise, respectively. The context sentences are split into atomic facts using 
    deepseek-chat, and the entailment probabilities are max-aggregated across atomic facts to get the attribution
    scores for the complete answer sentence. This is a naive version because we only consider individual
    source sentences, disregarding that they might need context from adjacent sentences to be understandable.
    """

    class NLIDataset(utils.data.Dataset):
        """Contains all pairs of sentences between a single answer sentence and all context sentences."""

        def __init__(self, answer_sent: str, context_sents: List[str]):
            self.answer_sent = answer_sent
            self.context_sents = context_sents 

        def __len__(self):
            return len(self.context_sents) 

        def __getitem__(self, idx):
            return self.answer_sent, self.context_sents[idx]


    atomic_facts = res["decomposed_model_answer"]
    attr_scores = []
    for atomic_facts_sent in atomic_facts:
        if not atomic_facts_sent:
            attr_scores.append(np.zeros(len(cc.sources)).tolist())
            continue

        attr_scores_sent = []
        for fact in atomic_facts_sent:
            # use torch dataloader for batch processing
            dataset = NLIDataset(fact, cc.sources)
            dataloader = DataLoader(dataset, shuffle=False, batch_size=cc.batch_size)

            # get entailment probs between atomic fact from answer sentence and all context sentences
            entailment_probs = get_nli_entailment_probs(nli_tokenizer, nli_model, dataloader)
            attr_scores_sent.append(entailment_probs)  
        # max aggregation
        attr_scores_sent = np.array(attr_scores_sent)
        attr_scores_sent = np.max(attr_scores_sent, axis=0)
        attr_scores.append(attr_scores_sent.tolist())

    # write to results dict
    res["methods"]["nli_post_hoc_naive"] = {
        "attr_scores": attr_scores,
    }
    return res

def compute_attributions_nli_post_hoc_sliding_window(cc: ContextCiter, sliding_window_lengths: List[int], 
                                                 nli_tokenizer: Union[PreTrainedTokenizer, PreTrainedTokenizerFast], 
                                                 nli_model: PreTrainedModel, res: dict):
    """
    Compute answer attribution scores using post-hoc attribution with the DeBERTa model for natural language 
    inference for each sentence in the model answer. We take as attribution scores the predicted probability
    for entailment from the NLI model using atomic facts from the answer sentence to attribute as hypothesis 
    and parts of the context as premise. We use a sliding window approach to use a specified number of adjacent 
    sentences as context and compute the attribution scores for the individual sentences by averaging all scores 
    for the windows that the sentence was included in.
    """

    class NLIDatasetSlidingWindows(utils.data.Dataset):
        """Contains all pairs of sentences between a single answer sentence and all context windows."""

        def __init__(self, answer_sent: str, context_windows: List[str]):
            self.answer_sent = answer_sent
            self.context_windows = context_windows 

        def __len__(self):
            return len(self.context_windows) 

        def __getitem__(self, idx):
            return self.answer_sent, self.context_windows[idx]
        
    def get_context_windows(source_sentences, window_length):
        """
        Group the source sentences into chunks/windows of _window_length_ sentences.
        Add padding such that we are starting and ending with chunks of single sentences.
        """

        padding = 2 * (window_length // 2)  # len(context_windows) = len(source_sentences) + padding

        start_idxs = np.arange(-padding, len(source_sentences))
        start_idxs = np.where(start_idxs < 0, 0, start_idxs) # minimum starting index is 0
        end_idxs = np.arange(1, len(source_sentences)+1+padding)
        end_idxs = np.where(end_idxs > len(source_sentences), len(source_sentences), end_idxs)    # maximum ending index is len(source_sentences), not strictly necessary but for understanding

        context_windows = []
        for start_idx, end_idx in zip(start_idxs, end_idxs):
            context_windows.append(" ".join(source_sentences[start_idx:end_idx]))

        return context_windows
        
    def aggregate_windows(scores, window_length):
        """
        Aggregate scores (entailment probabilities) for the windows to individual sentences (mean over the window scores where the sentence was in).
        Equivalent to 1D conv with kernel = 1/window_length * np.ones(window_length) with no padding.
        """

        padding = 2 * (window_length // 2)   # number of entries that get dropped (len(sources) = len(scores) - padding)

        aggregated_scores = []
        for i in range(len(scores)-padding):
            aggregated_scores.append(np.mean(scores[i:i+window_length]))

        return np.array(aggregated_scores)


    atomic_facts = res["decomposed_model_answer"]
    for window_length in sliding_window_lengths:
        context_windows = get_context_windows(cc.sources, window_length)

        attr_scores = []
        for atomic_facts_sent in atomic_facts:
            if not atomic_facts_sent:
                attr_scores.append(np.zeros(len(cc.sources)).tolist())
                continue

            attr_scores_sent = []
            for fact in atomic_facts_sent:
                # use torch dataloader for batch processing
                dataset = NLIDatasetSlidingWindows(fact, context_windows)
                dataloader = DataLoader(dataset, shuffle=False, batch_size=cc.batch_size)

                # get entailment probs between answer sentence and all context windows
                entailment_probs = get_nli_entailment_probs(nli_tokenizer, nli_model, dataloader)

                # aggregate scores
                entailment_probs = aggregate_windows(entailment_probs, window_length)
                attr_scores_sent.append(entailment_probs)
            # max aggregation
            attr_scores_sent = np.array(attr_scores_sent)
            attr_scores_sent = np.max(attr_scores_sent, axis=0)
            attr_scores.append(attr_scores_sent.tolist())

        # write results for each window length to results dict
        res["methods"][f"nli_post_hoc_sliding_window_{window_length}"] = {
            "attr_scores": attr_scores,
        }
    return res

def compute_attributions_nli_post_hoc_greedy_sampling(cc: ContextCiter, nli_tokenizer: Union[PreTrainedTokenizer, PreTrainedTokenizerFast], 
                                                      nli_model: PreTrainedModel, res: dict):
    """
    Generate citations using an NLI-based post-hoc attribution approach with greedy sampling based on the ADiOSAA framework from the paper
    "Post-Hoc Answer Attribution for Grounded and Trustworthy Long Document Comprehension: Task, Insights, and Challenges". This approach aggregates
    a list of cited source sentences. In each iteration it adds the one source sentence that maximizes entailment probability for the given atomic 
    fact from the answer sentence when combined with the already cited sentences. The method gives a list of cited sentences which
    can be used for top-k log-prob drop calculation but not for linear datamodeling score calculation. 
    """

    class NLIDatasetGreedySampling(utils.data.Dataset):
        """Combining context sentences for Optimal Selection logic from ADiOSAA-paper"""

        def __init__(self, answer_sentence: str, context_sentences: List[str]):
            self.answer_sentence = answer_sentence
            self.context_sentences = context_sentences 

            self.cited_sentences_idxs = []
            self.remaining_sentences_idxs = list(range(len(self.context_sentences)))

            # list with the contexts that are checked for entailment
            # contexts are joined sentences from the already selected context sentences
            # plus each one of the remaining sentences, respectively
            # at initialization, these are simply all the individual context sentences 
            self.contexts = context_sentences

        def __len__(self):
            return len(self.contexts)

        def __getitem__(self, idx):
            return self.answer_sentence, self.contexts[idx]

        def update(self, new_cited_sentence_idx):
            """
            Update the dataset for the next iteration of the algorithm based on which
            sentence was cited from the previous iteration (i.e. which sentence from 
            the remaining sentences resulted in the highest entailment probability
            when added to the already cited sentences).

            This function gets the sentence index for the sentence that gets added in 
            the latest iteration, adds it to the cited_sentences and removes it from 
            the remaining_sentences. Then it updates the contexts to check entailment
            for, for the next iteration. The contexts now all include the newly cited
            sentence and get combined with the now remaining_sentences which do not
            include the newly cited sentence anymore. I.e. for each iteration/for each
            added cited sentence the length of self.contexts gets reduced by 1.
            """

            self.cited_sentences_idxs.append(new_cited_sentence_idx)
            self.remaining_sentences_idxs.remove(new_cited_sentence_idx)

            # build new contexts
            contexts = []
            for idx in self.remaining_sentences_idxs:
                context_idxs = self.cited_sentences_idxs + [idx] # add one remaining sentence to the context
                context_idxs = sorted(context_idxs) # sort context sentences to join the in their original order
                contexts.append(" ".join([self.context_sentences[context_idx] for context_idx in context_idxs]))

            self.contexts = contexts

    # hyperparameter for stopping criterion
    delta_prob = 0.1

    atomic_facts = res["decomposed_model_answer"]
    attr_scores = []
    citations = []
    for i, atomic_facts_sent in enumerate(atomic_facts):
        if not atomic_facts_sent:
            attr_scores.append(np.zeros(len(cc.sources)).tolist())
            citations.append([])
            continue

        # number of source sentences to compute attribution score for; minimum 5 or as many as LongCite cited (if applicable) if it is more than 5
        k = 5
        if res["methods"].get("longcite_llm_direct"):
            n = len(res["methods"]["longcite_llm_direct"]["citations"][i])
            if n > 5:
                k = n 
        k = min(k, len(cc.sources))  # avoid bug where we try to cite more sources then there are

        attr_scores_sent = []
        citations_sent = []
        for fact in atomic_facts_sent:
            attr_scores_fact = -1 * np.ones(len(cc.sources))
            dataset = NLIDatasetGreedySampling(fact, cc.sources)
            prev_prob = 0.0
            stop = False

            for _ in range(k):
                dataloader = DataLoader(dataset, shuffle=False, batch_size=cc.batch_size)
                entailment_probs = get_nli_entailment_probs(nli_tokenizer, nli_model, dataloader)
                curr_prob = np.max(entailment_probs)
                new_cited_sentence_idx = dataset.remaining_sentences_idxs[np.argmax(entailment_probs)]
                dataset.update(new_cited_sentence_idx)
                attr_scores_fact[new_cited_sentence_idx] = curr_prob - prev_prob  

                # check stopping criterion and add citation
                if not stop:
                    if curr_prob - prev_prob >= delta_prob:
                        citations_sent.append(new_cited_sentence_idx)
                    else: 
                        stop = True

                prev_prob = curr_prob
            attr_scores_sent.append(attr_scores_fact)
        # aggregate attr_scores and citations
        attr_scores_sent = np.array(attr_scores_sent)
        attr_scores_sent = np.max(attr_scores_sent, axis=0)
        attr_scores.append(attr_scores_sent.tolist())
        citations.append(list(set(citations_sent)))

    # write results to results dict
    res["methods"]["nli_post_hoc_greedy_sampling"] = {
        "attr_scores": attr_scores,
        "citations": citations,
    }
    return res

def compute_attributions_llm_post_hoc(cc: ContextCiter, model: PreTrainedModel, tokenizer: Union[PreTrainedTokenizer, PreTrainedTokenizerFast], res: dict):
    """
    Generate citations by prompting an LLM for all answer sentences. The model is prompted to generate either
    k=1,3,5 citations to the top-k most relevant source sentences. The cited source sentences get assigned an 
    attribution score of 1, the others are assigned a score of 0. The scores can only be used to compute the 
    top-k log-probability drop but not the linear datamodeling score since this method does not generate an
    order of importance for all source sentences. Additionally the model is prompted to generate k = #citations 
    from LongCite model. Also, the model is prompted without any constraints on how many citations to generate.
    """

    def get_prompt_text(atomic_facts: List[str], context_sentences: List[str], k: int = None):
        # format context sentences with sentence indices
        context_sentences_numbered = []
        for i, sent in enumerate(context_sentences, start=1):
            context_sentences_numbered.append(f"[{i}] {sent}")
        context_sentences_numbered = "\n".join(context_sentences_numbered)

        # format atomic facts from the answer statement
        atomic_facts_formatted = "\n".join(atomic_facts)

        # build few-shot examples
        citations_1 = [5,3,6,8,9]
        citations_2 = [8, 1, 11, 2, 5]
        if k:
            cite_str_1 = "".join(f"[{i}]" for i in citations_1[:k])
            cite_str_2 = "".join(f"[{i}]" for i in citations_2[:k])
        else:
            cite_str_1 = "".join(f"[{i}]" for i in citations_1[:2])
            cite_str_2 = "".join(f"[{i}]" for i in citations_2[:2])
        example = f"Example 1:\nSource sentences:\n[1] There are several large and clear signs across all of the car parks we manage which outline the terms and conditions of parking within that establishment, and by choosing to park in the car park (whether they choose to read the signs or not) the motorist is entering into a contract where they agree to abide by those terms and conditions.\n[2] Many motorists believe that parking charges levied by parking companies are illegal and can be ignored without consequence, however this is simply not true.\n[3] If the parking company takes you to court and you lose you'll have to pay the fine, which could go up by then, you might have to pay court costs and these could be expensive. If you win, you won't have to pay the fine and the parking company might have to pay court costs. Pay and make a small claim to get the money back. If you don't want the parking company to take you to court, you should pay your parking ticket. This will stop the fine going up.\n[4] If you wish to challenge a parking fine, follow the instructions on the reverse of the notice and submit a written challenge within 14 days of issue to the South Wales Parking Group using the link below.\n[5] Ignoring official correspondence from reputable companies, such as Gemini Parking Solutions, could lead to an unnecessary and completely avoidable court cases.\n[6] Let the parking company take you to court. You can choose not to pay your parking ticket and the parking company will decide if it's worth taking you to court.\n[7] It's free to appeal and the notice to owner will tell you how.\n[8] Because Gemini Parking Solutions is a reputable company who displays these terms and conditions properly and within the confines of the law, every single parking charge we choose to issue in enforceable in the civil courts.\n[9] The council can then take you to court, your credit rating might be affected and you might also have to pay court costs.\n[10] Check on the notice if you must use the parking company's website or if you can write to them with your reasons for objecting.\n[11] We take a large number of motorists to court each month and, in fact, the judge always finds in our favour on the grounds that we are operating within the confines of the law and our parking charges are issued correctly, so the charge given is fair.\n\nStatements:\nThe evidence shows that ignoring a parking charge notice could lead to an unnecessary and completely avoidable court case.\n\nCitations:{cite_str_1}\n\nExample 2:\nSource sentences:\n[1] There are several large and clear signs across all of the car parks we manage which outline the terms and conditions of parking within that establishment, and by choosing to park in the car park (whether they choose to read the signs or not) the motorist is entering into a contract where they agree to abide by those terms and conditions.\n[2] Many motorists believe that parking charges levied by parking companies are illegal and can be ignored without consequence, however this is simply not true.\n[3] If the parking company takes you to court and you lose you'll have to pay the fine, which could go up by then, you might have to pay court costs and these could be expensive. If you win, you won't have to pay the fine and the parking company might have to pay court costs. Pay and make a small claim to get the money back. If you don't want the parking company to take you to court, you should pay your parking ticket. This will stop the fine going up.\n[4] If you wish to challenge a parking fine, follow the instructions on the reverse of the notice and submit a written challenge within 14 days of issue to the South Wales Parking Group using the link below.\n[5] Ignoring official correspondence from reputable companies, such as Gemini Parking Solutions, could lead to an unnecessary and completely avoidable court cases.\n[6] Let the parking company take you to court. You can choose not to pay your parking ticket and the parking company will decide if it's worth taking you to court.\n[7] It's free to appeal and the notice to owner will tell you how.\n[8] Because Gemini Parking Solutions is a reputable company who displays these terms and conditions properly and within the confines of the law, every single parking charge we choose to issue in enforceable in the civil courts.\n[9] The council can then take you to court, your credit rating might be affected and you might also have to pay court costs.\n[10] Check on the notice if you must use the parking company's website or if you can write to them with your reasons for objecting.\n[11] We take a large number of motorists to court each month and, in fact, the judge always finds in our favour on the grounds that we are operating within the confines of the law and our parking charges are issued correctly, so the charge given is fair.\n\nStatements:\nGemini Parking Solutions is a reputable company operating within the confines of the law.\nGemini Parking Solutions issues parking charges correctly.\nThe parking charges given by Gemini Parking Solutions are fair.\n\nCitations:{cite_str_2}"

        if k:
            system_prompt_template = "You are an expert fact-checker. You are given one or multiple statements which are atomic facts from a sentence, and sources in the form of a list of source sentences numbered with sentence indices. The source sentences contain information which is more or less relevant for the given statements. Your task is to identify the exact sentences from the provided list of source sentences that are most relevant for the given statements and that you would cite as sources supporting the statements. A single source sentence does not have to support all statements. A source sentence can be highly relevant even if it supports only a subset of the statements. You must only use the provided context to solve this task and respond only with the sentence indices in square brackets. You must provide exactly {k} sentence indices for the {k} most relevant source sentences. Respond only with the sentence indices and end your answer immediately after doing so. Respond with no additional text.\n\n{example}"
            user_prompt_template = "Identify the {k} most relevant sentences from the provided list of source sentences that directly support or provide evidence for the provided statements. Respond only with the sentence indices in square brackets.\n\nSource sentences:\n{context_sentences}\n\nStatements:\n{atomic_facts}\n\nCitations:"

            system_prompt_text = system_prompt_template.format(k=k, example=example)
            user_prompt_text = user_prompt_template.format(k=k, context_sentences=context_sentences_numbered, atomic_facts=atomic_facts_formatted)

        else:
            system_prompt_template = "You are an expert fact-checker. You are given one or multiple statements, and sources in the form of a list of source sentences numbered with sentence indices. The source sentences contain information which is more or less relevant for the given statements. Your task is to identify the exact sentences from the provided list of source sentences that are most relevant for the given statements and that you would cite as sources supporting the statements. You must only use the provided context to solve this task and respond only with the sentence indices in square brackets. You should provide 1-3 sentence indices for the 1-3 most relevant source sentences. IMPORTANT: Do not cite more than 3 sentences, your output should be at most 3 sentence indices. Do not cite source sentences that do not add any further evidence to support the claims. Stop citing further source sentences when the already cited source sentences provide enough evidence to fully support the statements. Respond only with the sentence indices and end your answer immediately after doing so. Respond with no additional text.\n\n{example}"
            user_prompt_template = "Identify the most relevant sentences from the provided list of source sentences that directly support or provide evidence for the provided statements. Remember to provide at most 3 sentence indices. Respond only with the sentence indices in square brackets.\n\nSource sentences:\n{context_sentences}\n\nStatements:\n{atomic_facts}\n\nCitations:"

            system_prompt_text = system_prompt_template.format(example=example)
            user_prompt_text = user_prompt_template.format(context_sentences=context_sentences_numbered, atomic_facts=atomic_facts_formatted)

        return system_prompt_text, user_prompt_text
    
    def get_prompt_ids(system_prompt_text, user_prompt_text, model, tokenizer, device):
        # use appropriate chat template depending on the model
        if model.config._name_or_path == "meta-llama/Llama-3.1-8B-Instruct":
            messages = [
                {'role': 'system',
                'content': system_prompt_text},
                {'role': 'user',
                'content': user_prompt_text}
            ]
            prompt_ids = tokenizer.apply_chat_template(
                messages,
                add_generation_prompt=True,
                return_tensors="pt",
                return_dict=True,
            ).to(device)

        return prompt_ids
    
    def extract_sentence_indices(model_answer, eos_token, n_sources, k=None):
        # ensure the model did not generate endlessly
        if not eos_token in model_answer:
            return None
        # extract indices with simple reg_ex
        reg_ex = re.compile(r"\[\s*(\d+)\s*\]")
        sentence_indices = reg_ex.findall(model_answer)
        sentence_indices = [int(idx) for idx in sentence_indices]
        sentence_indices = list(dict.fromkeys(sentence_indices))  # remove duplicates
        sentence_indices = np.array(sentence_indices, dtype=int)

        # validate
        if k:
            if len(sentence_indices) < k:
                return None
            else:
                sentence_indices = sentence_indices[:k] # if too many citations were generated still count as valid and take first k
        if np.any(sentence_indices <= 0) or np.any(sentence_indices > n_sources):
            return None
        return sentence_indices 
    
    def prompt_model(model, tokenizer, system_prompt_text, user_prompt_text, generate_kwargs):
        input_ids = get_prompt_ids(system_prompt_text, user_prompt_text, model, tokenizer, model.device)
        with torch.inference_mode():
            output_ids = model.generate(**input_ids, **generate_kwargs)
        output_text = tokenizer.decode(output_ids.squeeze()[input_ids["input_ids"].shape[1]:])
        return output_text 
    
    def get_model_output(model, tokenizer, system_prompt_text, user_prompt_text, cc, k=None):
        n_tries = 5
        for try_i in range(n_tries):
            if try_i == 0:
                generate_kwargs = {"do_sample": False, "max_new_tokens": 50}
            else:
                generate_kwargs = {"do_sample": True, "temperature": 1.0, "max_new_tokens": 50}

            output_text = prompt_model(model, tokenizer, system_prompt_text, user_prompt_text, generate_kwargs)
            # extract the sentence indices for the cited sentences from the model answer & check if they are valid
            sentence_indices = extract_sentence_indices(output_text, tokenizer.eos_token, len(cc.sources), k)

            # return results if they are valid
            if sentence_indices is not None:
                return output_text, sentence_indices
            
        return output_text, None


    atomic_facts = res["decomposed_model_answer"]
    attr_scores, citations, model_generations = [], [], []
    for i, atomic_facts_sent in enumerate(atomic_facts):
        if not atomic_facts_sent:
            attr_scores.append(None)
            citations.append([])
            model_generations.append(None)
            continue

        attr_scores_sent, model_generations_sent = {}, {}  # for LLM post-hoc the attribution scores for one sentence is a dict with entries for k=1,3,5,k_longcite

        #--- attribution with specified k=1,3,5,k_longcite for top-k log-prob drop calculation ---#
        # how many sources to cite; append number of sources as LongCite cited (if applicable)
        ks = [1,3,5]
        if res["methods"].get("longcite_llm_direct"):
            n = len(res["methods"]["longcite_llm_direct"]["citations"][i])
            if n not in ks and n >= 1:
                ks.append(n)
                ks = sorted(ks)

        for k in ks:
            # build prompt and perform inference
            system_prompt_text, user_prompt_text = get_prompt_text(atomic_facts_sent, cc.sources, k)
            output_text, sentence_indices = get_model_output(model, tokenizer, system_prompt_text, user_prompt_text, cc, k)
            model_generations_sent[f"{k}"] = output_text

            if sentence_indices is not None: 
                sentence_indices = sentence_indices - 1 # sub 1 to get array indices since the source indices start with 1 instead of 0
                attr_scores_sent_k = np.zeros(len(cc.sources))
                attr_scores_sent_k[sentence_indices] = 1  # set attr_scores to 1 for all cited sentences, else 0
                attr_scores_sent[f"{k}"] = attr_scores_sent_k.tolist()
            else:
                attr_scores_sent[f"{k}"] = None  

        #--- generate citations without constraining the amount of cited source sentences ---#
        # build prompt and perform inference
        system_prompt_text, user_prompt_text = get_prompt_text(atomic_facts_sent, cc.sources, k=None)
        output_text, sentence_indices = get_model_output(model, tokenizer, system_prompt_text, user_prompt_text, cc, k=None)
        model_generations_sent["k_self"] = output_text

        if sentence_indices is not None: 
            sentence_indices = sentence_indices - 1 # sub 1 to get array indices since the source indices start with 1 instead of 0
            citations_sent = sentence_indices.tolist()
            k_self = len(citations_sent)
            if k_self not in ks:
                attr_scores_sent_k = np.zeros(len(cc.sources))
                attr_scores_sent_k[sentence_indices] = 1  # set attr_scores to 1 for all cited sentences, else 0
                attr_scores_sent[f"{k_self}"] = attr_scores_sent_k.tolist()
        else:
            citations_sent = []
 
        attr_scores.append(attr_scores_sent)
        citations.append(citations_sent)
        model_generations.append(model_generations_sent)

    # write results to results dict
    res["methods"]["llm_post_hoc"] = {
        "attr_scores": attr_scores,
        "citations": citations,
        "model_generations": model_generations,
    }
    return res

def compute_attributions_longcite(cc: LongCiteContextCiter, res: dict):
    """Direct attribution using LongCite model."""

    longcite_result = cc.response_dict
    citations = [] 
    for statement in longcite_result["all_statements"]:
        if statement["statement"].strip():
            citation = statement["citation"]
            statement_citations = []
            if citation:
                for cite in citation:
                    statement_citations.extend(list(range(cite["start_sentence_idx"], cite["end_sentence_idx"]+1)))
            citations.append(statement_citations)

    attr_scores = []
    for statement_citations in citations:
        attr_scores_sent = np.zeros(len(cc.sources))
        if len(statement_citations) > 0:
            attr_scores_sent[statement_citations] = 1    # set attr_scores to 1 for all cited sentences, else 0
        attr_scores.append(attr_scores_sent.tolist())
    
    res["methods"]["longcite_llm_direct"] = {
        "attr_scores": attr_scores,
        "citations": citations,
    }
    return res
    
#--- Answer Attribution Methods end ---#

def main(config=None):

    if config is None:
        config = parse_args()

    load_dotenv()
    HF_TOKEN = os.getenv("HF_TOKEN")

    # log into huggingface
    login(token=HF_TOKEN)

    # load data and model
    use_model = (("longcite_llm_direct" in config.attr_methods) or ("llm_post_hoc" in config.attr_methods) 
                 or ("context_cite" in config.attr_methods))
    model, tokenizer, device = load_model(config.model_name, True, use_model=use_model) 
    data = load_data(config.dataset, n_samples=config.n_samples, start_idx=config.start_idx, seed=0)

    # load sentence embedding model if semantic similarity is used for attribution
    if "semantic_similarity" in config.attr_methods:
        sentence_embedding_model = SentenceTransformer("all-mpnet-base-v2")

    # load DeBERTa NLI model for post-hoc answer attribution
    use_nli = ("nli_post_hoc_naive" in config.attr_methods 
        or "nli_post_hoc_sliding_window" in config.attr_methods 
        or "nli_post_hoc_greedy_sampling" in config.attr_methods)
    if (use_nli):
        model_name = "MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli"
        device = "cuda" if torch.cuda.is_available() else "cpu"
        nli_tokenizer = AutoTokenizer.from_pretrained(model_name)
        nli_model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)

    PROMPT_TEMPLATE = LONGCITE_PROMPT_TEMPLATE if config.use_longcite else load_cc_prompt_template(config.dataset)  # LongCite prompt template is not actually used
    GENERATE_KWARGS = LONGCITE_GENERATE_KWARGS if config.use_longcite else CC_GENERATE_KWARGS

    # load or make results file
    results_path = Path(config.results_path)
    if not results_path.exists():
        # make new results file and save metadata
        results_path.parent.mkdir(parents=True, exist_ok=True)
        results_path.touch()
        results = {}

        results["metadata"] = {
            "dataset": config.dataset,
            "model": config.model_name,
        }
        results["metadata"]["cc_args"] = {
            "batch_size": config.cc_batch_size,
            "prompt_template": PROMPT_TEMPLATE,
            "generate_kwargs": GENERATE_KWARGS,
        }
        results["results"] = []
    else:
        # load existing results file to append the new results to
        results = load_json(results_path)

        # check that the old experiment used the same dataset
        assert results["metadata"]["dataset"] == config.dataset, "Existing results should come from the same dataset as new results to compute."

    for idx, data_point in tqdm(enumerate(data, start=config.start_idx), total=len(data)):
        # check if other results for this data point exist already, if not add new entry
        if len(results["results"]) > idx:   # exists already
            data_point_results = results["results"][idx]    # copy old results to extend/overwrite
        else:  
            # make new entry 
            data_point_results = {  
                "instance_idx": idx,
            }
            results["results"].append(data_point_results)

        context, query = load_datapoint(data_point, config.dataset, config.use_longcite) # depends on the given dataset
        partitioner = LongCiteContextPartitioner(context=context) if config.use_longcite else None

        # instantiate ContextCiter to use for answer attribution (used by baselines; for attribution with ContextCite 
        # we have to instantiate new ContextCiter objects with corresponding num_ablations).
        cc_kwargs = {
            "model": model,
            "tokenizer": tokenizer,
            "context": context,
            "query": query,
            "batch_size": config.cc_batch_size,
            "prompt_template": PROMPT_TEMPLATE,
            "generate_kwargs": GENERATE_KWARGS,
            "partitioner": partitioner,
        }
        cc = LongCiteContextCiter(**cc_kwargs) if config.use_longcite else ContextCiter(**cc_kwargs)

        # save meta information and add key structure to the dict to save attribution scores;
        # if information already exists from previous run then load the model output into the ContextCiter object
        data_point_results, cc = get_results_metadata(cc, data_point_results)

        #--- perform answer attribution using the different methods ---#
        try:
            if "longcite_llm_direct" in config.attr_methods:
                data_point_results = compute_attributions_longcite(cc, data_point_results)

            if "context_cite" in config.attr_methods:
                data_point_results = compute_attributions_context_cite(cc_kwargs, data_point_results, config.cc_num_ablations, config.use_longcite)

            if "semantic_similarity" in config.attr_methods:
                data_point_results = compute_attributions_semantic_similarity(cc, sentence_embedding_model, data_point_results)

            if "leave_one_out" in config.attr_methods:
                data_point_results = compute_attributions_leave_one_out(cc, data_point_results)

            if "llm_post_hoc" in config.attr_methods:
                data_point_results = compute_attributions_llm_post_hoc(cc, model, tokenizer, data_point_results)

            #--- NLI-based attribution methods ---#
            if "nli_post_hoc_naive" in config.attr_methods:
                data_point_results = compute_attributions_nli_post_hoc_naive(cc, nli_tokenizer, nli_model, data_point_results)

            if "nli_post_hoc_sliding_window" in config.attr_methods:
                data_point_results = compute_attributions_nli_post_hoc_sliding_window(cc, config.sliding_window_lengths, nli_tokenizer, nli_model, data_point_results)

            if "nli_post_hoc_greedy_sampling" in config.attr_methods:
                data_point_results = compute_attributions_nli_post_hoc_greedy_sampling(cc, nli_tokenizer, nli_model, data_point_results)

        except KeyboardInterrupt:
            print("\nKeyboard interrupt! Saving data...")
            save_json(results_path, results)
            break
        except torch.cuda.OutOfMemoryError as e:
            print("Cuda out of memory error!")
            print(idx)
            print('-'*200)
            data_point_results = {}  # make results for this data point invalid
            # cleanup
            del cc
            del model 
            gc.collect()
            torch.cuda.empty_cache()
            # load new model
            try:
                model, _, _ = load_model(config.model_name, True, use_model=use_model)
            except Exception as reload_error:
                print(f"Failed to reaload model: {reload_error}\n\nStopping script...")
                break
        except Exception as e:
            traceback.print_exc()
            print('-'*200)
            # print(e)
            # continue 
            raise e

        # add results for the data point to the results
        results["results"][idx] = data_point_results

        # save every 5 data points
        if (idx+1) % 5 == 0:
            save_json(results_path, results)

    # finally save all results to result file
    save_json(results_path, results)

if __name__ == "__main__":
    main()