import argparse
import os
import gc 
import traceback
from pathlib import Path
from datasets import Dataset
import numpy as np 
import torch
import warnings
from copy import copy 
from scipy.stats import spearmanr, ConstantInputWarning
from dotenv import load_dotenv 
from huggingface_hub import login
from context_cite import ContextCiter
from context_cite.utils import _get_response_logit_probs, aggregate_logit_probs
from tqdm.auto import tqdm
from typing import List 
from numpy.typing import NDArray
from utils import load_json, save_json, load_data, load_datapoint, load_cc_prompt_template, load_model, CC_GENERATE_KWARGS
from longcite_utils import LongCiteContextCiter, LongCiteContextPartitioner, LONGCITE_GENERATE_KWARGS, LONGCITE_PROMPT_TEMPLATE

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

def parse_args():
    parser = argparse.ArgumentParser(description="Calculate top-k log-prob drop (k=1,3,5) and linear datamodeling score for different attribution methods.") 
    parser.add_argument("--attr_methods", type=str, nargs="+", choices=["context_cite_32", "context_cite_64", "context_cite_128", "context_cite_256", "semantic_similarity", "leave_one_out", "nli_post_hoc_naive", "nli_post_hoc_sliding_window_3", "nli_post_hoc_sliding_window_5", "nli_post_hoc_greedy_sampling", "llm_post_hoc", "longcite_llm_direct"], default=None, help="Which answer attribution methods to calculate the metrics for.")
    parser.add_argument("--metrics", type=str, nargs="+", choices=["log_prob_drop", "LDS"], default=["log_prob_drop", "LDS"], help="Which metric(s) to compute.")
    parser.add_argument("--dataset", type=str, choices=["cnn_daily_mail", "druid"], required=True, help="Which dataset to use.")
    parser.add_argument("--model_name", type=str, choices=["meta-llama/Llama-3.1-8B-Instruct"], default="meta-llama/Llama-3.1-8B-Instruct", help="Huggingface name of model to use.")
    parser.add_argument("--use_longcite", action="store_true", help="Whether to use the ContextCiter class modified for use with LongCite model and tokenizer and whether to calculate top-k log-prob drop with k = #citations from LongCite model.")
    parser.add_argument("--results_path", type=str, default="Results/results.json", help="Path to the file where attribution scores and experiment results (metrics) are stored.")
    parser.add_argument("--n_samples", type=int, default=20, help="For how many data points to compute the metrics.")
    parser.add_argument("--start_idx", type=int, default=0, help="Data starting index.")
    parser.add_argument("--m", type=int, default=128, help="How many random ablation vectors to sample for LDS calculation.")
    parser.add_argument("--cc_batch_size", type=int, default=8, help="Batch size to use in ContextCiter for performing inference using ablated contexts.")

    return parser.parse_args()

#--- Metric Functions ---#
def calc_top_k_log_prob_drop(cc: ContextCiter, res: dict, attr_methods: List[str], use_longcite: bool):
    """
    Calculate top-k log-probability drop metric for a single data point.
    Calculate metric each for k=1,3,5 and for each sentence in the answer.
    Also calculate for k = #citations generated by LongCite if use_longcite is True.
    """

    def create_mask(attr_scores: List, k: int) -> NDArray[np.bool_]:
        """Create a boolean mask based on given attribution scores and number of top-sources to ablate (k)."""

        mask = np.ones(len(attr_scores), dtype=np.bool_)

        if k == 0:  # full mask without ablations
            pass
        
        else:
            top_k_idxs = np.argsort(attr_scores)[-k:]
            mask[top_k_idxs] = False

        return mask
    
    def create_dataset(cc: ContextCiter, masks: List[NDArray[np.bool_]]):
        """
        Create "dataset" with input tokens and output tokens (labels) for different ablations.
        Based on ContextCite utils._create_regression_dataset function.
        """

        data_dict = {
            "input_ids": [],
            "attention_mask": [],
            "labels": [],
        }

        response_ids = cc._response_ids # token indices of the complete response
        for mask in masks:
            prompt_ids = cc._get_prompt_ids(mask=mask)  # token indices of the prompt with sources ablated according to the mask
            input_ids = prompt_ids + response_ids

            data_dict["input_ids"].append(input_ids)
            data_dict["attention_mask"].append([1] * len(input_ids))
            data_dict["labels"].append([-100] * len(prompt_ids) + response_ids) # label only for response part

        return Dataset.from_dict(data_dict)
    
    # how many sources to ablate
    Ks = [0,1,3,5]

    answer_statements = res["answer_statements"]
    char_spans = res["answer_statement_char_spans"]

    # loop through attribution methods and sentences, then for each sentence compute
    # top-k log-prob drop for k=1,3,5
    attr_methods = attr_methods or res["methods"].keys()
    for attr_method in attr_methods:

        # prepare results dict
        if "metrics" not in res["methods"][attr_method].keys():
            res["methods"][attr_method]["metrics"] = {}
        if "top_k_drop" not in res["methods"][attr_method]["metrics"].keys():
            res["methods"][attr_method]["metrics"]["top_k_drop"] = {}
        for k in Ks[1:]:
            res["methods"][attr_method]["metrics"]["top_k_drop"][f"top_{k}_drop"] = []  # for each method and k, there is a list of drops (drop for each sentence)
        if use_longcite:
            res["methods"][attr_method]["metrics"]["top_k_drop"]["top_k_drop_longcite"] = []  # for k = #citations by LongCite

        for sent_idx, (start_idx, end_idx) in zip(range(len(answer_statements)), char_spans):
            # add k = #citations by LongCite if used
            ks = Ks
            if use_longcite:
                k_longcite = len(res["methods"]["longcite_llm_direct"]["citations"][sent_idx])
                if k_longcite not in Ks:
                    ks.append(k_longcite)

            # 0. load attribution scores
            attr_scores = res["methods"][attr_method]["attr_scores"][sent_idx] 

            # special case: attribution via prompting LLM; then we have different attribution scores for each k (except k=0 where we have no attributions)
            if attr_method == "llm_post_hoc":
                attr_scores_ks = [attr_scores[f"{k}"] if k != 0 else np.zeros(len(cc.sources)) for k in ks]

                # check if the LLM generated any invalid citations for any k, i.e. if there are entries that are None
                if np.any([attr_score is None for attr_score in attr_scores_ks]):
                    # skip calculations for the current sentence and write None as result
                    for k in Ks[1:]:
                        res["methods"][attr_method]["metrics"]["top_k_drop"][f"top_{k}_drop"].append(None)
                    if use_longcite:
                        res["methods"][attr_method]["metrics"]["top_k_drop"]["top_k_drop_longcite"].append(None)
                    continue

            else:   # simply repeat attribution scores for how many different ks we have for all other attribution methods since they are identical
                attr_scores_ks = len(ks) * [attr_scores]

            # 1. create masks for k=1,3,5 and create one full mask where no sources are ablated (k=0) for computing the difference 
            masks = []
            for attr_scores_k, k in zip(attr_scores_ks, ks):
                masks.append(create_mask(attr_scores_k, k))

            # 2. create "dataset" with input tokens for different ablations and output tokens (labels) 
            dataset = create_dataset(cc, masks)

            # 3. calculate logit probabilities for all answer tokens for each of the context ablations
            # shape: (n_masks, n_answer_tokens)
            logit_probs = _get_response_logit_probs(
                dataset, cc.model, cc.tokenizer, len(cc._response_ids), cc.batch_size
            )

            # 4. aggregate logit_probs and convert to log_prob for the current sentence
            ids_start_idx, ids_end_idx = cc._indices_to_token_indices(start_idx, end_idx)
            logit_probs_sent = logit_probs[:, ids_start_idx:ids_end_idx]

            log_probs = []  # final log probabilites for the answer with context ablations according to k=0,1,3,5
            for i in range(len(ks)):
                log_probs.append(aggregate_logit_probs(logit_probs_sent[i:i+1,:], output_type="log_prob"))

            # 5. compute differences with full context, normalize the result by number of answer tokens (in the sentence)
            n_answer_tokens_sent = logit_probs_sent.shape[1]
            for i,k in enumerate(ks[1:], start=1):
                diff = (log_probs[0] - log_probs[i]) / n_answer_tokens_sent # diff full_context - ablated_context

                # write result to the results dict (append to list for sentences)
                if use_longcite and k not in Ks:
                    res["methods"][attr_method]["metrics"]["top_k_drop"]["top_k_drop_longcite"].append(diff.item())
                else:
                    res["methods"][attr_method]["metrics"]["top_k_drop"][f"top_{k}_drop"].append(diff.item())
                
    return res

def calc_linear_datamodeling_score(cc: ContextCiter, res: dict, attr_methods: List[str]):
    """Calculate linear datamodeling score metric for each sentence for a single data point."""

    def prepare_results_dict(res: dict, attr_methods: List[str]):
        """Add key-structure to the results dict for saving the LDS scores."""

        for attr_method in attr_methods:
            if "metrics" not in res["methods"][attr_method].keys():
                res["methods"][attr_method]["metrics"] = {}
            res["methods"][attr_method]["metrics"]["LDS"] = []  # list of scores (one LDS score per sentence)

        return res 

    attr_methods = attr_methods or res["methods"].keys()

    if "llm_post_hoc" in attr_methods:
        warnings.warn("Can not calculate linear datamodeling score for LLM-post-hoc attribution method. Skipping calculations...")
        attr_methods = copy(attr_methods)
        attr_methods.remove("llm_post_hoc")

    if "nli_post_hoc_greedy_sampling" in attr_methods:
        warnings.warn("Can not calculate linear datamodeling score for NLI-based post-hoc attribution method with greedy sampling. Skipping calculations...")
        attr_methods = copy(attr_methods)
        attr_methods.remove("nli_post_hoc_greedy_sampling")

    if "longcite_llm_direct" in attr_methods:
        warnings.warn("Can not calculate linear datamodeling score for LLM direct attribution. Skipping calculations...")
        attr_methods = copy(attr_methods)
        attr_methods.remove("longcite_llm_direct")

    res = prepare_results_dict(res, attr_methods)

    # get logit probs for each context ablation and answer token
    logit_probs = cc._logit_probs  # (m, n_answer_tokens)
    masks = cc._masks   # (m, n_sources)

    # loop through sentences and attribution methods, then for each sentence compute LDS
    answer_statements = res["answer_statements"]
    char_spans = res["answer_statement_char_spans"]
    for sent_idx, (start_idx, end_idx) in zip(range(len(answer_statements)), char_spans):

        # aggregate logit_probs for the current sentence to get the true response generation probabilities f
        ids_start_idx, ids_end_idx = cc._indices_to_token_indices(start_idx, end_idx)
        logit_probs_sent = logit_probs[:, ids_start_idx:ids_end_idx]        # (m, n_tokens_sent)
        f = aggregate_logit_probs(logit_probs_sent, output_type="log_prob") # (m,)

        # compare true probabilities with predicted probabilities for each attribution method
        for attr_method in attr_methods:

            # load attribution scores for the current sentence and method
            attr_scores = np.array(res["methods"][attr_method]["attr_scores"][sent_idx])

            # calculate predicted probs by summing the attribution scores corresponding to the non-ablated sources
            f_hat = masks @ attr_scores # (m, n_sources) x (n_sources) -> (m,)

            # compute Spearman rank correlation
            # NOTE: catch warning for when any input is constant, i.e. answer sentence does not depend at all on
            # the context sentences; then set the LDS score to None and ignore it for calculating the mean later
            # (None will be converted to null when saving to json, back to None when loading from json and to np.nan
            # when converting the data to np.array when setting dtype=float where it can then be ignored using np.nanmean()
            # OR the entire sentence could be excluded)
            with warnings.catch_warnings():
                warnings.filterwarnings("error", category=ConstantInputWarning)

                try:
                    LDS = spearmanr(f, f_hat).statistic.item()
                except ConstantInputWarning:
                    LDS = None
    
            # write result to the results dict (append to list for sentences)
            res["methods"][attr_method]["metrics"]["LDS"].append(LDS)

    return res
#--- Metric Functions ---#


def main(config=None):

    if config is None:
        config = parse_args()

    # load results file
    results_path = Path(config.results_path)
    results = load_json(results_path)

    # check to use same dataset and model as for computing the attribution scores
    assert results["metadata"]["dataset"] == config.dataset, "Existing results should come from the same dataset as new results to compute."
    assert results["metadata"]["model"] == config.model_name, "Existing results should use the same language model as new results to compute."

    load_dotenv()

    # log into huggingface
    HF_TOKEN = os.getenv("HF_TOKEN")
    login(token=HF_TOKEN)

    # load data and model
    model, tokenizer, device = load_model(config.model_name, True) 
    data = load_data(config.dataset, n_samples=config.n_samples, start_idx=config.start_idx, seed=0)

    PROMPT_TEMPLATE = LONGCITE_PROMPT_TEMPLATE if config.use_longcite else load_cc_prompt_template(config.dataset)  # LongCite prompt template is not actually used
    GENERATE_KWARGS = LONGCITE_GENERATE_KWARGS if config.use_longcite else CC_GENERATE_KWARGS

    for idx, data_point in tqdm(enumerate(data, start=config.start_idx), total=len(data)):

        data_point_results = results["results"][idx]
        # skip if results are empty
        if not data_point_results:
            continue

        context, query = load_datapoint(data_point, config.dataset) # depends on the given dataset
        partitioner = LongCiteContextPartitioner(context=context) if config.use_longcite else None

        # instantiate ContextCiter for probability calculations
        cc_kwargs = {
            "model": model,
            "tokenizer": tokenizer,
            "context": context,
            "query": query,
            "num_ablations": config.m,  # number of ablations for LDS calculation; doesn't matter for log-prob drop
            "batch_size": config.cc_batch_size,
            "prompt_template": PROMPT_TEMPLATE,
            "generate_kwargs": GENERATE_KWARGS,
            "partitioner": partitioner,
        }
        cc = LongCiteContextCiter(**cc_kwargs) if config.use_longcite else ContextCiter(**cc_kwargs)
        cc._cache["output"] = data_point_results["model_output_full"]  # set original model output

        try:
            if "log_prob_drop" in config.metrics:
                # calculate top-k log-probability drop metric
                data_point_results = calc_top_k_log_prob_drop(cc, data_point_results, config.attr_methods, config.use_longcite)

            if "LDS" in config.metrics:
                # calculate linear datamodeling score metric
                data_point_results = calc_linear_datamodeling_score(cc, data_point_results, config.attr_methods)

        except KeyboardInterrupt:
            print("\nKeyboard interrupt! Saving data...")
            break
        except torch.cuda.OutOfMemoryError as e:
            print("Cuda out of memory error!")
            print(idx)
            print('-'*200)
            # cleanup
            del cc
            del model 
            gc.collect()
            torch.cuda.empty_cache()
            # load new model
            try:
                model, _, _ = load_model(config.model_name, True)
            except Exception as reload_error:
                print(f"Failed to reaload model: {reload_error}\n\nStopping script...")
                break
            continue
        except Exception as e:
            traceback.print_exc()
            print('-'*200)
            # print(e)
            # continue 
            raise e

        # add results for the data point to the results
        results["results"][idx] = data_point_results

        # save every 5 data points
        if (idx+1) % 5 == 0:
            save_json(results_path, results)

    # finally save all results to result file
    save_json(results_path, results)

if __name__ == "__main__":
    main()